# Generated by Django 4.2.2 on 2023-06-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
